# Generated by Django 3.2.4 on 2021-06-10 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.TextField(default=1623299627.448716)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='authentication.profile')),
                ('like_users', models.ManyToManyField(related_name='liked_posts', to='authentication.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.TextField(default=1623299627.448716)),
                ('updated_at', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('like_users', models.ManyToManyField(related_name='liked_comments', to='authentication.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting.posting')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycomments', to='authentication.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
