# Generated by Django 3.2.4 on 2021-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623306594.0796201),
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_at',
            field=models.TextField(default=1623306594.0796201),
        ),
    ]
