# Generated by Django 3.2.4 on 2021-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20210610_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623314686.516445),
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_at',
            field=models.TextField(default=1623314686.516445),
        ),
        migrations.AlterField(
            model_name='posting',
            name='photo',
            field=models.ImageField(upload_to='posting_pics'),
        ),
    ]
