# Generated by Django 3.2.4 on 2021-06-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_profile_created_at'),
        ('posting', '0003_auto_20210610_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623318649.729716),
        ),
        migrations.AlterField(
            model_name='posting',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_at',
            field=models.TextField(default=1623318649.729716),
        ),
        migrations.AlterField(
            model_name='posting',
            name='like_users',
            field=models.ManyToManyField(related_name='liked_postings', to='authentication.Profile'),
        ),
    ]
