# Generated by Django 3.2.4 on 2021-06-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20210611_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623886772.5195851),
        ),
        migrations.AlterField(
            model_name='posting',
            name='created_at',
            field=models.TextField(default=1623886772.5195851),
        ),
    ]
