version: '3.7'
services:
  dev:
    container_name: deve
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: sh -c "python manage.py runserver 0:9000"
    volumes:
      - .:/django/
    ports:
      - '9000:9000'
  nginx:
    image: nginx:latest
    container_name: nginx_produ
    ports:
      - '80:80'
    volumes:
      - .:/django
      - ./config/nginx/:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - produ
  produ:
    container_name: produ
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/django/
