# Generated by Django 3.2.4 on 2021-06-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.TextField(default=1623887006.549155),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/logos/profile_pic/close-button-png-30230.png', null=True, upload_to='profile_pic'),
        ),
    ]
