# Generated by Django 3.2.4 on 2021-06-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210617_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img_url',
            field=models.TextField(default='https://django-s3-practice-1.s3.ap-northeast-2.amazonaws.com/avatar.jpg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.TextField(default=1624516038.283731),
        ),
    ]
