# Generated by Django 3.2.4 on 2021-06-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_auto_20210610_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='target_relationship', to='authentication.Profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='authentication.profile')),
            ],
        ),
    ]
